<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Meal;
use App\Models\Ingredient;
use App\Models\User;

class MealSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get or create a default user
        $user = User::firstOrCreate(
            ['email' => 'admin@smartpantry.local'],
            ['name' => 'Admin', 'password' => bcrypt('password')]
        );

        $meals = [
            // PASTA DISHES (10)
            ['name' => 'Chicken Fried Rice', 'description' => 'Classic Asian-style fried rice with chicken pieces, vegetables, and soy sauce', 'image' => 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 350, 'prep_time' => 25, 'ingredients' => ['chicken', 'rice', 'soy sauce', 'garlic', 'carrot', 'onion']],
            ['name' => 'Tomato Basil Pasta', 'description' => 'Fresh pasta with aromatic tomato sauce and basil garnish', 'image' => 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 420, 'prep_time' => 30, 'ingredients' => ['pasta', 'tomato', 'basil', 'garlic', 'olive oil', 'parmesan cheese']],
            ['name' => 'Fettuccine Alfredo', 'description' => 'Creamy pasta with rich parmesan and butter sauce', 'image' => 'https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 480, 'prep_time' => 20, 'ingredients' => ['pasta', 'parmesan cheese', 'butter', 'cream', 'garlic']],
            ['name' => 'Spaghetti Carbonara', 'description' => 'Classic Italian pasta with eggs, cheese, and pancetta', 'image' => 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 520, 'prep_time' => 25, 'ingredients' => ['pasta', 'eggs', 'parmesan cheese', 'black pepper', 'butter']],
            ['name' => 'Penne Arrabbiata', 'description' => 'Spicy tomato pasta with garlic and red chili', 'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 20, 'ingredients' => ['pasta', 'tomato', 'garlic', 'chili powder', 'olive oil']],
            ['name' => 'Spinach and Cheese Pasta', 'description' => 'Creamy pasta with fresh spinach and melted cheddar cheese', 'image' => 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 450, 'prep_time' => 28, 'ingredients' => ['pasta', 'spinach', 'cheddar cheese', 'milk', 'butter', 'garlic']],
            ['name' => 'Seafood Linguine', 'description' => 'Delicate pasta with shrimp, mussels, and clams in white wine', 'image' => 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 410, 'prep_time' => 35, 'ingredients' => ['pasta', 'shrimp', 'mussels', 'clams', 'garlic', 'olive oil', 'lemon']],
            ['name' => 'Meat Bolognese', 'description' => 'Rich pasta sauce with ground beef, tomatoes, and herbs', 'image' => 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 490, 'prep_time' => 45, 'ingredients' => ['pasta', 'beef', 'tomato', 'onion', 'garlic', 'oregano', 'basil']],
            ['name' => 'Shrimp and Garlic Pasta', 'description' => 'Simple yet elegant pasta with succulent shrimp and plenty of garlic', 'image' => 'https://images.unsplash.com/photo-1563393577875-320a93b1d307?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 390, 'prep_time' => 25, 'ingredients' => ['pasta', 'shrimp', 'garlic', 'olive oil', 'lemon', 'parmesan cheese', 'black pepper']],
            ['name' => 'Mushroom Pasta', 'description' => 'Creamy mushroom pasta with fresh herbs', 'image' => 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 400, 'prep_time' => 25, 'ingredients' => ['pasta', 'mushroom', 'cream', 'garlic', 'thyme', 'butter', 'salt']],
            // RICE (10)
            ['name' => 'Mushroom Risotto', 'description' => 'Creamy Italian rice dish with sautéed mushrooms and parmesan', 'image' => 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 400, 'prep_time' => 35, 'ingredients' => ['rice', 'mushroom', 'onion', 'garlic', 'butter', 'parmesan cheese', 'salt']],
            ['name' => 'Shrimp Fried Rice', 'description' => 'Quick stir-fry rice with shrimp and eggs', 'image' => 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 20, 'ingredients' => ['rice', 'shrimp', 'eggs', 'garlic', 'soy sauce', 'green beans']],
            ['name' => 'Vegetable Fried Rice', 'description' => 'Healthy fried rice packed with colorful vegetables', 'image' => 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 280, 'prep_time' => 20, 'ingredients' => ['rice', 'carrot', 'corn', 'peas', 'onion', 'garlic', 'soy sauce']],
            ['name' => 'Beef Fried Rice', 'description' => 'Hearty fried rice with tender beef and vegetables', 'image' => 'https://images.unsplash.com/photo-1606850780554-b55ea4dd0b70?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 420, 'prep_time' => 25, 'ingredients' => ['rice', 'beef', 'eggs', 'onion', 'garlic', 'soy sauce', 'carrot']],
            ['name' => 'Pineapple Fried Rice', 'description' => 'Tropical Thai-style rice with pineapple', 'image' => 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 350, 'prep_time' => 20, 'ingredients' => ['rice', 'pineapple', 'chicken', 'onion', 'garlic', 'soy sauce']],
            ['name' => 'Spanish Rice', 'description' => 'Tomato and spice flavored rice with vegetables', 'image' => 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 290, 'prep_time' => 30, 'ingredients' => ['rice', 'tomato', 'onion', 'bell pepper', 'garlic', 'cumin', 'paprika']],
            ['name' => 'Teriyaki Chicken Rice', 'description' => 'Sweet and savory chicken served over steamed white rice', 'image' => 'https://images.unsplash.com/photo-1603073163308-9654c3fb70b5?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 420, 'prep_time' => 30, 'ingredients' => ['rice', 'chicken', 'soy sauce', 'honey', 'ginger', 'garlic', 'sesame oil']],
            ['name' => 'Red Beans and Rice', 'description' => 'Traditional creole dish with kidney beans and rice', 'image' => 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 350, 'prep_time' => 35, 'ingredients' => ['rice', 'kidney beans', 'onion', 'garlic', 'celery', 'thyme', 'bay leaf']],
            ['name' => 'Lemon Herb Rice', 'description' => 'Fragrant rice infused with fresh lemon and herbs', 'image' => 'https://images.unsplash.com/photo-1605231079479-5b4d0538e62e?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 250, 'prep_time' => 20, 'ingredients' => ['rice', 'lemon', 'parsley', 'thyme', 'olive oil', 'salt', 'garlic']],
            ['name' => 'Seafood Paella', 'description' => 'Spanish rice dish with shrimp, mussels, and saffron', 'image' => 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 480, 'prep_time' => 45, 'ingredients' => ['rice', 'shrimp', 'mussels', 'tomato', 'onion', 'garlic', 'saffron']],
            // MEAT (15)
            ['name' => 'Beef Stir Fry', 'description' => 'Quick and savory beef stir fry with fresh vegetables and ginger', 'image' => 'https://images.unsplash.com/photo-1606850780554-b55ea4dd0b70?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 22, 'ingredients' => ['beef', 'bell pepper', 'onion', 'garlic', 'ginger', 'soy sauce', 'olive oil']],
            ['name' => 'Grilled Chicken Breast', 'description' => 'Perfectly grilled chicken breast with lemon and herbs', 'image' => 'https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 300, 'prep_time' => 25, 'ingredients' => ['chicken', 'lemon', 'olive oil', 'thyme', 'garlic', 'salt']],
            ['name' => 'Baked Chicken with Potato and Carrot', 'description' => 'Wholesome one-pan roasted chicken with root vegetables', 'image' => 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 420, 'prep_time' => 50, 'ingredients' => ['chicken', 'potato', 'carrot', 'onion', 'olive oil', 'oregano', 'salt', 'black pepper']],
            ['name' => 'Chicken and Broccoli', 'description' => 'Tender chicken breast with fresh steamed broccoli and garlic sauce', 'image' => 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 320, 'prep_time' => 25, 'ingredients' => ['chicken', 'broccoli', 'garlic', 'soy sauce', 'ginger', 'olive oil']],
            ['name' => 'Pork Chops with Apple', 'description' => 'Golden pork chops paired with caramelized apples and onions', 'image' => 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 410, 'prep_time' => 30, 'ingredients' => ['pork', 'apple', 'onion', 'butter', 'thyme', 'salt']],
            ['name' => 'Lamb Stew', 'description' => 'Slow-cooked lamb with root vegetables and herbs', 'image' => 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 480, 'prep_time' => 90, 'ingredients' => ['lamb', 'potato', 'carrot', 'onion', 'garlic', 'thyme', 'bay leaf']],
            ['name' => 'Duck Confit', 'description' => 'Tender duck leg slow-cooked in its own fat', 'image' => 'https://images.unsplash.com/photo-1580554530778-ca36943938b2?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 550, 'prep_time' => 120, 'ingredients' => ['duck', 'salt', 'thyme', 'rosemary', 'garlic']],
            ['name' => 'Turkey Meatballs', 'description' => 'Lean turkey meatballs in tomato sauce with pasta', 'image' => 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 35, 'ingredients' => ['turkey', 'tomato', 'onion', 'garlic', 'bread', 'eggs', 'parmesan cheese']],
            ['name' => 'Beef Tacos', 'description' => 'Seasoned ground beef in soft tortillas with toppings', 'image' => 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 420, 'prep_time' => 20, 'ingredients' => ['beef', 'tortilla', 'tomato', 'onion', 'cilantro', 'cumin', 'lime']],
            ['name' => 'Pork Stir Fry', 'description' => 'Quick pork stir fry with ginger and soy sauce', 'image' => 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 360, 'prep_time' => 20, 'ingredients' => ['pork', 'bell pepper', 'onion', 'garlic', 'ginger', 'soy sauce', 'sesame oil']],
            ['name' => 'Chicken Tikka Masala', 'description' => 'Spiced chicken in creamy tomato sauce', 'image' => 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 450, 'prep_time' => 45, 'ingredients' => ['chicken', 'yogurt', 'tomato', 'onion', 'garlic', 'ginger', 'cumin', 'turmeric']],
            ['name' => 'Beef Wellington', 'description' => 'Tender beef wrapped in mushroom duxelles and pastry', 'image' => 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 580, 'prep_time' => 60, 'ingredients' => ['beef', 'mushroom', 'onion', 'garlic', 'thyme', 'butter', 'bread']],
            ['name' => 'Turkey Schnitzel', 'description' => 'Breaded and pan-fried turkey cutlets', 'image' => 'https://images.unsplash.com/photo-1600803966845-b341359cb68c?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 370, 'prep_time' => 20, 'ingredients' => ['turkey', 'flour', 'eggs', 'bread', 'lemon', 'olive oil', 'salt']],
            ['name' => 'Lamb Kofta', 'description' => 'Spiced lamb skewers with yogurt sauce', 'image' => 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 420, 'prep_time' => 30, 'ingredients' => ['lamb', 'onion', 'garlic', 'cumin', 'cilantro', 'yogurt', 'mint']],
            ['name' => 'Chicken Marsala', 'description' => 'Pan-seared chicken in mushroom wine sauce', 'image' => 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 25, 'ingredients' => ['chicken', 'mushroom', 'garlic', 'butter', 'salt', 'black pepper']],
            // SEAFOOD (12)
            ['name' => 'Grilled Fish with Lemon', 'description' => 'Perfectly grilled fish fillet seasoned with fresh lemon and herbs', 'image' => 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 280, 'prep_time' => 20, 'ingredients' => ['fish', 'lemon', 'garlic', 'olive oil', 'salt', 'black pepper']],
            ['name' => 'Baked Salmon', 'description' => 'Herb-crusted baked salmon with roasted vegetables', 'image' => 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 420, 'prep_time' => 30, 'ingredients' => ['salmon', 'dill', 'lemon', 'olive oil', 'salt', 'black pepper']],
            ['name' => 'Fish Tacos', 'description' => 'Crispy fish in soft tortillas with cabbage slaw', 'image' => 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 350, 'prep_time' => 25, 'ingredients' => ['fish', 'tortilla', 'cabbage', 'lime', 'cilantro', 'mayonnaise']],
            ['name' => 'Shrimp Scampi', 'description' => 'Garlic butter shrimp served with pasta', 'image' => 'https://images.unsplash.com/photo-1633504581786-316c8002b1b9?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 15, 'ingredients' => ['shrimp', 'garlic', 'butter', 'lemon', 'parsley']],
            ['name' => 'Crab Cakes', 'description' => 'Crispy crab and breadcrumb patties with lemon aioli', 'image' => 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 360, 'prep_time' => 30, 'ingredients' => ['crab', 'bread', 'eggs', 'mayonnaise', 'mustard', 'lemon']],
            ['name' => 'Tuna Poke Bowl', 'description' => 'Marinated tuna served over sushi rice with vegetables', 'image' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 420, 'prep_time' => 15, 'ingredients' => ['tuna', 'rice', 'soy sauce', 'ginger', 'sesame oil', 'avocado', 'cucumber']],
            ['name' => 'Lobster Bisque', 'description' => 'Creamy soup with chunks of tender lobster', 'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 45, 'ingredients' => ['lobster', 'onion', 'garlic', 'cream', 'butter', 'salt']],
            ['name' => 'Codfish Steak', 'description' => 'Pan-seared cod with seasonal vegetables', 'image' => 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 300, 'prep_time' => 20, 'ingredients' => ['cod', 'lemon', 'garlic', 'olive oil', 'bell pepper', 'zucchini']],
            ['name' => 'Seafood Pasta', 'description' => 'Mixed shellfish pasta in garlic white wine sauce', 'image' => 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 410, 'prep_time' => 30, 'ingredients' => ['pasta', 'shrimp', 'mussels', 'garlic', 'olive oil', 'lemon', 'parsley']],
            ['name' => 'Halibut Meuniere', 'description' => 'Delicate white fish cooked in brown butter sauce', 'image' => 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 320, 'prep_time' => 20, 'ingredients' => ['halibut', 'butter', 'lemon', 'parsley', 'salt', 'black pepper']],
            ['name' => 'Shrimp Curry', 'description' => 'Spicy shrimp in coconut curry sauce', 'image' => 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 350, 'prep_time' => 30, 'ingredients' => ['shrimp', 'coconut milk', 'onion', 'garlic', 'ginger', 'cumin', 'turmeric']],
            ['name' => 'Mussels in White Wine', 'description' => 'Steamed mussels in garlic and white wine broth', 'image' => 'https://images.unsplash.com/photo-1523682249883-ddce3e1dd455?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 280, 'prep_time' => 20, 'ingredients' => ['mussels', 'onion', 'garlic', 'butter', 'parsley']],
            // VEGETABLES (10)
            ['name' => 'Grilled Vegetables with Herb Oil', 'description' => 'Mixed grilled vegetables with aromatic herb-infused oil', 'image' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 210, 'prep_time' => 20, 'ingredients' => ['broccoli', 'zucchini', 'bell pepper', 'olive oil', 'garlic', 'oregano', 'salt']],
            ['name' => 'Chickpea Curry', 'description' => 'Aromatic Indian curry with chickpeas and coconut milk', 'image' => 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 40, 'ingredients' => ['chickpeas', 'tomato', 'onion', 'garlic', 'coconut milk', 'cumin', 'cilantro']],
            ['name' => 'Vegetable Stir Fry', 'description' => 'Colorful mix of fresh vegetables with soy ginger sauce', 'image' => 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 250, 'prep_time' => 20, 'ingredients' => ['broccoli', 'bell pepper', 'carrot', 'onion', 'garlic', 'ginger', 'soy sauce']],
            ['name' => 'Stuffed Bell Peppers', 'description' => 'Bell peppers filled with rice, vegetables, and cheese', 'image' => 'https://images.unsplash.com/photo-1598679253544-2c97992403ea?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 320, 'prep_time' => 45, 'ingredients' => ['bell pepper', 'rice', 'onion', 'garlic', 'tomato', 'cheese', 'cilantro']],
            ['name' => 'Ratatouille', 'description' => 'Classic French vegetable stew with eggplant and zucchini', 'image' => 'https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 230, 'prep_time' => 45, 'ingredients' => ['eggplant', 'zucchini', 'bell pepper', 'tomato', 'onion', 'garlic', 'oregano']],
            ['name' => 'Lentil Soup', 'description' => 'Hearty lentil and vegetable soup with lemon', 'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 280, 'prep_time' => 40, 'ingredients' => ['lentils', 'onion', 'garlic', 'carrot', 'celery', 'tomato', 'lemon']],
            ['name' => 'Asparagus with Garlic', 'description' => 'Tender asparagus sautéed with garlic and lemon', 'image' => 'https://images.unsplash.com/photo-1515516969-d4008cc6241a?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 160, 'prep_time' => 10, 'ingredients' => ['asparagus', 'garlic', 'lemon', 'olive oil', 'salt']],
            ['name' => 'Cauliflower Curry', 'description' => 'Roasted cauliflower in aromatic spice curry', 'image' => 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 320, 'prep_time' => 35, 'ingredients' => ['cauliflower', 'onion', 'garlic', 'ginger', 'cumin', 'turmeric', 'coconut milk']],
            ['name' => 'Eggplant Parmesan', 'description' => 'Breaded eggplant layers with tomato sauce and cheese', 'image' => 'https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 420, 'prep_time' => 50, 'ingredients' => ['eggplant', 'tomato', 'mozzarella', 'parmesan cheese', 'flour', 'eggs', 'basil']],
            ['name' => 'Green Beans with Almonds', 'description' => 'Crispy green beans with toasted almond slivers', 'image' => 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 200, 'prep_time' => 15, 'ingredients' => ['green beans', 'butter', 'garlic', 'salt']],
            // SALADS (8)
            ['name' => 'Spinach Salad', 'description' => 'Fresh spinach salad with light olive oil dressing', 'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 150, 'prep_time' => 10, 'ingredients' => ['spinach', 'olive oil', 'lemon', 'garlic', 'salt', 'black pepper']],
            ['name' => 'Greek Salad', 'description' => 'Fresh vegetables with feta cheese and olives', 'image' => 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 220, 'prep_time' => 10, 'ingredients' => ['tomato', 'cucumber', 'onion', 'feta cheese', 'olive oil', 'lemon', 'oregano']],
            ['name' => 'Caesar Salad', 'description' => 'Romaine lettuce with creamy Caesar dressing and parmesan', 'image' => 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 280, 'prep_time' => 10, 'ingredients' => ['lettuce', 'parmesan cheese', 'bread', 'mayonnaise', 'lemon', 'garlic']],
            ['name' => 'Caprese Salad', 'description' => 'Fresh tomato, mozzarella, and basil with balsamic vinegar', 'image' => 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 240, 'prep_time' => 5, 'ingredients' => ['tomato', 'mozzarella', 'basil', 'olive oil', 'balsamic vinegar', 'salt']],
            ['name' => 'Quinoa Salad', 'description' => 'Nutritious quinoa with vegetables and lemon dressing', 'image' => 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 310, 'prep_time' => 20, 'ingredients' => ['quinoa', 'cucumber', 'tomato', 'onion', 'parsley', 'lemon', 'olive oil']],
            ['name' => 'Coleslaw', 'description' => 'Crispy cabbage salad with creamy vinaigrette', 'image' => 'https://images.unsplash.com/photo-1625938145744-e38051539994?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 180, 'prep_time' => 10, 'ingredients' => ['cabbage', 'carrot', 'mayonnaise', 'vinegar', 'sugar', 'salt']],
            ['name' => 'Arugula Salad', 'description' => 'Peppery arugula with parmesan and lemon oil', 'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 170, 'prep_time' => 5, 'ingredients' => ['arugula', 'parmesan cheese', 'lemon', 'olive oil', 'salt']],
            ['name' => 'Beet and Goat Cheese Salad', 'description' => 'Roasted beets with creamy goat cheese and walnuts', 'image' => 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 290, 'prep_time' => 25, 'ingredients' => ['goat cheese', 'arugula', 'olive oil', 'lemon']],
            // SOUPS (8)
            ['name' => 'Tomato Soup', 'description' => 'Smooth tomato soup with basil and cream', 'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 220, 'prep_time' => 30, 'ingredients' => ['tomato', 'onion', 'garlic', 'cream', 'basil', 'salt']],
            ['name' => 'Minestrone', 'description' => 'Hearty Italian vegetable and pasta soup', 'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 280, 'prep_time' => 45, 'ingredients' => ['pasta', 'tomato', 'onion', 'garlic', 'kidney beans', 'basil']],
            ['name' => 'French Onion Soup', 'description' => 'Caramelized onion soup with cheese toast', 'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 320, 'prep_time' => 50, 'ingredients' => ['onion', 'bread', 'cheese', 'butter', 'thyme', 'salt']],
            ['name' => 'Chicken Noodle Soup', 'description' => 'Classic comforting soup with chicken and noodles', 'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 240, 'prep_time' => 30, 'ingredients' => ['chicken', 'noodles', 'carrot', 'celery', 'onion', 'salt']],
            ['name' => 'Vegetable Soup', 'description' => 'Light and healthy vegetable broth with mixed vegetables', 'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 180, 'prep_time' => 30, 'ingredients' => ['carrot', 'onion', 'celery', 'tomato', 'zucchini', 'salt']],
            ['name' => 'Creamy Mushroom Soup', 'description' => 'Rich mushroom soup with fresh herbs', 'image' => 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 280, 'prep_time' => 35, 'ingredients' => ['mushroom', 'onion', 'garlic', 'cream', 'thyme', 'butter', 'salt']],
            ['name' => 'Clam Chowder', 'description' => 'Creamy soup with clams, potatoes, and onions', 'image' => 'https://images.unsplash.com/photo-1594756202469-9ff9799b2e4e?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 45, 'ingredients' => ['clams', 'potato', 'onion', 'celery', 'cream', 'butter', 'salt']],
            ['name' => 'Pumpkin Soup', 'description' => 'Creamy pumpkin soup with warm spices', 'image' => 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 240, 'prep_time' => 40, 'ingredients' => ['onion', 'cinnamon', 'nutmeg', 'cream', 'butter']],
            // SANDWICHES (6)
            ['name' => 'Turkey Sandwich', 'description' => 'Classic turkey and cheese sandwich on bread', 'image' => 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 320, 'prep_time' => 10, 'ingredients' => ['turkey', 'bread', 'cheese', 'lettuce', 'tomato', 'mayonnaise']],
            ['name' => 'Pork Tacos', 'description' => 'Soft tortillas stuffed with seasoned pork and avocado', 'image' => 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 450, 'prep_time' => 30, 'ingredients' => ['pork', 'tortilla', 'avocado', 'onion', 'cilantro', 'lime']],
            ['name' => 'Avocado Toast', 'description' => 'Simple toast topped with mashed avocado and spices', 'image' => 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 220, 'prep_time' => 5, 'ingredients' => ['bread', 'avocado', 'salt', 'black pepper', 'lime']],
            ['name' => 'Chicken Wrap', 'description' => 'Grilled chicken with vegetables and ranch wrap', 'image' => 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 15, 'ingredients' => ['chicken', 'tortilla', 'lettuce', 'tomato', 'onion', 'mayonnaise']],
            ['name' => 'Falafel Sandwich', 'description' => 'Crispy chickpea fritters in pita with tahini sauce', 'image' => 'https://images.unsplash.com/photo-1593001874117-c99c800e3eb7?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 420, 'prep_time' => 30, 'ingredients' => ['chickpeas', 'bread', 'onion', 'garlic', 'cumin', 'tahini', 'lemon']],
            ['name' => 'Club Sandwich', 'description' => 'Triple-decker sandwich with turkey, bacon, and vegetables', 'image' => 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 580, 'prep_time' => 10, 'ingredients' => ['bread', 'turkey', 'cheese', 'lettuce', 'tomato', 'mayonnaise']],
            // BREAKFAST (11)
            ['name' => 'Pancakes', 'description' => 'Fluffy pancakes served with syrup and butter', 'image' => 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 520, 'prep_time' => 20, 'ingredients' => ['flour', 'milk', 'eggs', 'butter', 'sugar', 'baking powder']],
            ['name' => 'Scrambled Eggs', 'description' => 'Soft and creamy scrambled eggs with toast', 'image' => 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 280, 'prep_time' => 10, 'ingredients' => ['eggs', 'butter', 'bread', 'salt', 'black pepper', 'milk']],
            ['name' => 'Thai Coconut Curry', 'description' => 'Creamy Thai curry with vegetables and aromatic spices', 'image' => 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 360, 'prep_time' => 35, 'ingredients' => ['coconut milk', 'onion', 'garlic', 'ginger', 'bell pepper', 'cilantro', 'lime']],
            ['name' => 'Spinach and Feta Omelette', 'description' => 'Fluffy omelette filled with fresh spinach and feta cheese', 'image' => 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 320, 'prep_time' => 15, 'ingredients' => ['eggs', 'spinach', 'feta cheese', 'mushroom', 'butter', 'salt']],
            ['name' => 'French Toast', 'description' => 'Eggy bread slices topped with cinnamon and syrup', 'image' => 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 420, 'prep_time' => 15, 'ingredients' => ['bread', 'eggs', 'milk', 'cinnamon', 'sugar', 'butter', 'vanilla extract']],
            ['name' => 'Vegetable Frittata', 'description' => 'Baked egg dish with colorful vegetables and cheese', 'image' => 'https://images.unsplash.com/photo-1510693206972-df098062cb71?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 340, 'prep_time' => 30, 'ingredients' => ['eggs', 'mushroom', 'bell pepper', 'onion', 'cheese', 'butter', 'salt']],
            ['name' => 'Waffles with Berries', 'description' => 'Crispy waffles topped with fresh berries and whipped cream', 'image' => 'https://images.unsplash.com/photo-1562376552-0d160a2f238d?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 480, 'prep_time' => 20, 'ingredients' => ['flour', 'milk', 'eggs', 'butter', 'blueberry', 'sugar', 'baking powder']],
            ['name' => 'Shakshuka', 'description' => 'Eggs poached in spicy tomato sauce with peppers', 'image' => 'https://images.unsplash.com/photo-1590412200988-a436970781fa?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 300, 'prep_time' => 25, 'ingredients' => ['eggs', 'tomato', 'onion', 'garlic', 'bell pepper', 'cumin', 'paprika']],
            ['name' => 'Granola with Yogurt', 'description' => 'Greek yogurt topped with homemade granola and honey', 'image' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 5, 'ingredients' => ['yogurt', 'oats', 'honey', 'blueberry', 'cinnamon']],
            ['name' => 'Huevos Rancheros', 'description' => 'Fried eggs on tortillas with salsa and beans', 'image' => 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 450, 'prep_time' => 20, 'ingredients' => ['eggs', 'tortilla', 'tomato', 'onion', 'black beans', 'cilantro', 'lime']],
            ['name' => 'Smoothie Bowl', 'description' => 'Thick smoothie topped with granola and fresh fruit', 'image' => 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 340, 'prep_time' => 5, 'ingredients' => ['yogurt', 'strawberry', 'blueberry', 'banana', 'coconut milk', 'granola', 'honey']],
            // SUPERFOOD SALADS (10)
            ['name' => 'Kale and Quinoa Salad', 'description' => 'Nutritious kale salad with quinoa, avocado, and lemon tahini dressing', 'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 20, 'ingredients' => ['kale', 'quinoa', 'avocado', 'lemon', 'tahini', 'olive oil', 'chia seeds']],
            ['name' => 'Sweet Potato and Black Bean Salad', 'description' => 'Roasted sweet potato salad with black beans and lime dressing', 'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 350, 'prep_time' => 25, 'ingredients' => ['sweet potato', 'black beans', 'lime', 'cilantro', 'cumin', 'olive oil']],
            ['name' => 'Brussels Sprouts Salad', 'description' => 'Shaved Brussels sprouts with cranberries, pecans, and feta', 'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 290, 'prep_time' => 15, 'ingredients' => ['Brussels sprouts', 'cranberries', 'pecans', 'feta cheese', 'balsamic vinegar', 'olive oil']],
            ['name' => 'Mediterranean Chickpea Salad', 'description' => 'Chickpeas with cucumber, tomato, olives, and feta', 'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 340, 'prep_time' => 10, 'ingredients' => ['chickpeas', 'cucumber', 'tomato', 'feta cheese', 'olive oil', 'oregano', 'lemon']],
            ['name' => 'Farro Salad with Roasted Vegetables', 'description' => 'Ancient grain salad with seasonal roasted vegetables', 'image' => 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 360, 'prep_time' => 35, 'ingredients' => ['farro', 'zucchini', 'bell pepper', 'eggplant', 'feta cheese', 'olive oil', 'basil']],
            ['name' => 'Quinoa Buddha Bowl', 'description' => 'Protein-packed bowl with quinoa, roasted veggies, and tahini', 'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 420, 'prep_time' => 30, 'ingredients' => ['quinoa', 'sweet potato', 'broccoli', 'avocado', 'tahini', 'lemon', 'cumin']],
            ['name' => 'Collard Greens Salad', 'description' => 'Massaged collard greens with avocado and pumpkin seeds', 'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 280, 'prep_time' => 15, 'ingredients' => ['collard greens', 'avocado', 'pumpkin seeds', 'lemon', 'olive oil', 'garlic']],
            ['name' => 'Millet Salad with Herbs', 'description' => 'Light millet salad with fresh herbs and lemon vinaigrette', 'image' => 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 310, 'prep_time' => 25, 'ingredients' => ['millet', 'parsley', 'mint', 'cucumber', 'tomato', 'lemon', 'olive oil']],
            ['name' => 'Acai Berry Bowl', 'description' => 'Antioxidant-rich bowl with acai, banana, and granola', 'image' => 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 10, 'ingredients' => ['acai berries', 'banana', 'blueberry', 'granola', 'coconut milk', 'chia seeds']],
            // HEALTHY GRAIN BOWLS (10)
            ['name' => 'Chia Seed Pudding', 'description' => 'Creamy chia pudding with almond milk and fresh berries', 'image' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 280, 'prep_time' => 5, 'ingredients' => ['chia seeds', 'almond milk', 'blueberry', 'strawberry', 'cinnamon', 'maple syrup']],
            ['name' => 'Overnight Oats with Nuts', 'description' => 'Oats soaked overnight with nuts, seeds, and fruit', 'image' => 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 350, 'prep_time' => 5, 'ingredients' => ['oats', 'almond milk', 'chia seeds', 'almonds', 'banana', 'cinnamon']],
            ['name' => 'Buckwheat Porridge', 'description' => 'Nutritious buckwheat porridge with berries and nuts', 'image' => 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 320, 'prep_time' => 20, 'ingredients' => ['buckwheat', 'almond milk', 'blueberry', 'walnuts', 'cinnamon', 'maple syrup']],
            ['name' => 'Amaranth Breakfast Bowl', 'description' => 'Protein-rich amaranth with coconut and tropical fruits', 'image' => 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 340, 'prep_time' => 25, 'ingredients' => ['amaranth', 'coconut milk', 'mango', 'coconut', 'chia seeds', 'lime']],
            ['name' => 'Teff Porridge', 'description' => 'Ethiopian grain porridge with honey and nuts', 'image' => 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 310, 'prep_time' => 20, 'ingredients' => ['teff', 'almond milk', 'honey', 'pecans', 'cinnamon', 'banana']],
            ['name' => 'Quinoa Breakfast Bowl', 'description' => 'Savory quinoa with avocado, eggs, and greens', 'image' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 20, 'ingredients' => ['quinoa', 'eggs', 'avocado', 'spinach', 'tomato', 'feta cheese']],
            ['name' => 'Farro Risotto', 'description' => 'Creamy farro with mushrooms and parmesan', 'image' => 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 360, 'prep_time' => 35, 'ingredients' => ['farro', 'mushroom', 'onion', 'garlic', 'parmesan cheese', 'olive oil', 'thyme']],
            ['name' => 'Millet Risotto with Vegetables', 'description' => 'Nutty millet risotto with seasonal vegetables', 'image' => 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 340, 'prep_time' => 30, 'ingredients' => ['millet', 'zucchini', 'carrot', 'onion', 'parmesan cheese', 'olive oil', 'sage']],
            ['name' => 'Barley Bowl with Lentils', 'description' => 'Hearty barley and lentil bowl with spices', 'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 390, 'prep_time' => 40, 'ingredients' => ['barley', 'lentils', 'onion', 'garlic', 'cumin', 'turmeric', 'coconut milk']],
            ['name' => 'Polenta with Mushroom Ragout', 'description' => 'Creamy polenta topped with mushroom sauce', 'image' => 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 370, 'prep_time' => 35, 'ingredients' => ['polenta', 'mushroom', 'onion', 'garlic', 'thyme', 'olive oil', 'parmesan cheese']],
            // PLANT-BASED PROTEIN MEALS (10)
            ['name' => 'Tofu Stir Fry', 'description' => 'Crispy tofu with broccoli and ginger soy sauce', 'image' => 'https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 320, 'prep_time' => 25, 'ingredients' => ['tofu', 'broccoli', 'bell pepper', 'ginger', 'soy sauce', 'sesame oil', 'garlic']],
            ['name' => 'Tempeh Buddha Bowl', 'description' => 'Marinated tempeh with quinoa and roasted vegetables', 'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 420, 'prep_time' => 30, 'ingredients' => ['tempeh', 'quinoa', 'sweet potato', 'broccoli', 'tahini', 'lemon', 'cumin']],
            ['name' => 'Edamame Salad', 'description' => 'Fresh edamame with cucumber, carrot, and sesame dressing', 'image' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 280, 'prep_time' => 15, 'ingredients' => ['edamame', 'cucumber', 'carrot', 'sesame oil', 'rice vinegar', 'ginger', 'sesame seeds']],
            ['name' => 'Lentil and Sweet Potato Curry', 'description' => 'Spicy lentil curry with coconut milk and sweet potato', 'image' => 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 35, 'ingredients' => ['lentils', 'sweet potato', 'coconut milk', 'onion', 'garlic', 'curry powder', 'spinach']],
            ['name' => 'Chickpea and Spinach Curry', 'description' => 'Creamy chickpea curry with fresh spinach', 'image' => 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 360, 'prep_time' => 30, 'ingredients' => ['chickpeas', 'spinach', 'coconut milk', 'tomato', 'onion', 'garlic', 'cumin']],
            ['name' => 'Black Bean and Quinoa Bowl', 'description' => 'Protein-packed bowl with black beans, quinoa, and avocado', 'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 410, 'prep_time' => 25, 'ingredients' => ['black beans', 'quinoa', 'avocado', 'corn', 'lime', 'cilantro', 'cumin']],
            ['name' => 'Tofu Teriyaki Bowl', 'description' => 'Sweet and savory tofu with rice and steamed vegetables', 'image' => 'https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 30, 'ingredients' => ['tofu', 'rice', 'broccoli', 'carrot', 'soy sauce', 'honey', 'ginger', 'sesame seeds']],
            ['name' => 'Tempeh Tacos', 'description' => 'Spiced tempeh in corn tortillas with avocado salsa', 'image' => 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 360, 'prep_time' => 25, 'ingredients' => ['tempeh', 'tortilla', 'avocado', 'tomato', 'onion', 'lime', 'cilantro', 'cumin']],
            ['name' => 'Edamame Hummus Bowl', 'description' => 'Fresh edamame hummus with pita and vegetable sticks', 'image' => 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 340, 'prep_time' => 20, 'ingredients' => ['edamame', 'tahini', 'lemon', 'garlic', 'olive oil', 'bread', 'carrot', 'cucumber']],
            ['name' => 'Mushroom and Lentil Stew', 'description' => 'Hearty mushroom and lentil stew with herbs', 'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 320, 'prep_time' => 40, 'ingredients' => ['mushroom', 'lentils', 'onion', 'carrot', 'thyme', 'bay leaf', 'olive oil']],
            // NUT AND SEED RECIPES (10)
            ['name' => 'Almond Butter Toast', 'description' => 'Whole grain toast with almond butter and banana slices', 'image' => 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 320, 'prep_time' => 5, 'ingredients' => ['bread', 'almonds', 'banana', 'cinnamon', 'honey']],
            ['name' => 'Walnut and Goat Cheese Salad', 'description' => 'Mixed greens with walnuts, goat cheese, and balsamic', 'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 10, 'ingredients' => ['lettuce', 'walnuts', 'goat cheese', 'balsamic vinegar', 'olive oil', 'honey']],
            ['name' => 'Pecan Crusted Chicken', 'description' => 'Chicken breast coated with pecans and herbs', 'image' => 'https://images.unsplash.com/photo-1532636875304-0c89119d9b4e?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 420, 'prep_time' => 30, 'ingredients' => ['chicken', 'pecans', 'thyme', 'olive oil', 'garlic', 'salt']],
            ['name' => 'Pumpkin Seed Pesto Pasta', 'description' => 'Whole wheat pasta with pumpkin seed pesto and cherry tomatoes', 'image' => 'https://images.unsplash.com/photo-1563379091339-03246963d96c?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 20, 'ingredients' => ['pasta', 'pumpkin seeds', 'basil', 'garlic', 'parmesan cheese', 'olive oil', 'tomato']],
            ['name' => 'Sunflower Seed Energy Balls', 'description' => 'No-bake energy balls with oats, seeds, and dates', 'image' => 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 280, 'prep_time' => 15, 'ingredients' => ['oats', 'sunflower seeds', 'chia seeds', 'honey', 'cinnamon', 'vanilla extract']],
            ['name' => 'Flaxseed Crackers', 'description' => 'Homemade flaxseed crackers with herbs', 'image' => 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 220, 'prep_time' => 35, 'ingredients' => ['flaxseeds', 'water', 'sesame seeds', 'thyme', 'rosemary', 'salt']],
            ['name' => 'Hemp Seed Smoothie', 'description' => 'Green smoothie with hemp seeds, spinach, and banana', 'image' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 340, 'prep_time' => 5, 'ingredients' => ['hemp seeds', 'spinach', 'banana', 'almond milk', 'blueberry', 'chia seeds']],
            ['name' => 'Cashew Cream Sauce', 'description' => 'Creamy cashew sauce over roasted vegetables', 'image' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 360, 'prep_time' => 25, 'ingredients' => ['cashews', 'garlic', 'lemon', 'olive oil', 'broccoli', 'cauliflower', 'salt']],
            ['name' => 'Pistachio Crusted Fish', 'description' => 'White fish with pistachio crust and lemon herb sauce', 'image' => 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 380, 'prep_time' => 25, 'ingredients' => ['fish', 'pistachios', 'lemon', 'parsley', 'olive oil', 'garlic']],
            ['name' => 'Sesame Seed Stir Fry', 'description' => 'Vegetable stir fry with sesame seeds and ginger', 'image' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 320, 'prep_time' => 20, 'ingredients' => ['broccoli', 'bell pepper', 'carrot', 'sesame seeds', 'ginger', 'soy sauce', 'garlic']],
            // HEALTHY ROASTED VEGETABLES (10)
            ['name' => 'Roasted Brussels Sprouts', 'description' => 'Crispy roasted Brussels sprouts with balsamic glaze', 'image' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 180, 'prep_time' => 25, 'ingredients' => ['Brussels sprouts', 'balsamic vinegar', 'olive oil', 'garlic', 'salt']],
            ['name' => 'Butternut Squash Soup', 'description' => 'Creamy roasted butternut squash soup with sage', 'image' => 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 240, 'prep_time' => 45, 'ingredients' => ['butternut squash', 'onion', 'garlic', 'sage', 'vegetable broth', 'cream']],
            ['name' => 'Roasted Beet Hummus', 'description' => 'Beet-infused hummus with pita and vegetables', 'image' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 320, 'prep_time' => 30, 'ingredients' => ['beets', 'chickpeas', 'tahini', 'lemon', 'garlic', 'bread', 'carrot']],
            ['name' => 'Sweet Potato Mash', 'description' => 'Creamy mashed sweet potatoes with cinnamon', 'image' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 220, 'prep_time' => 30, 'ingredients' => ['sweet potato', 'butter', 'cinnamon', 'salt', 'milk']],
            ['name' => 'Acorn Squash Rings', 'description' => 'Baked acorn squash rings with maple glaze', 'image' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 160, 'prep_time' => 35, 'ingredients' => ['acorn squash', 'maple syrup', 'cinnamon', 'butter', 'salt']],
            ['name' => 'Roasted Pumpkin Seeds', 'description' => 'Spiced roasted pumpkin seeds as a healthy snack', 'image' => 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 280, 'prep_time' => 20, 'ingredients' => ['pumpkin seeds', 'olive oil', 'paprika', 'cumin', 'salt']],
            ['name' => 'Fennel and Orange Salad', 'description' => 'Shaved fennel salad with orange segments and olives', 'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 190, 'prep_time' => 15, 'ingredients' => ['fennel', 'orange', 'olive oil', 'lemon', 'salt', 'black pepper']],
            ['name' => 'Swiss Chard Saute', 'description' => 'Garlic-sautéed Swiss chard with lemon and pine nuts', 'image' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 140, 'prep_time' => 10, 'ingredients' => ['chard', 'garlic', 'lemon', 'olive oil', 'salt']],
            ['name' => 'Collard Green Wraps', 'description' => 'Large collard leaves stuffed with quinoa and vegetables', 'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 320, 'prep_time' => 25, 'ingredients' => ['collard greens', 'quinoa', 'avocado', 'tomato', 'tahini', 'lemon']],
            ['name' => 'Roasted Vegetable Medley', 'description' => 'Mixed roasted root vegetables with rosemary', 'image' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&h=400&fit=crop&auto=format&auto=webp&quality=80', 'calories' => 260, 'prep_time' => 40, 'ingredients' => ['carrot', 'beets', 'sweet potato', 'parsnip', 'rosemary', 'olive oil', 'salt']],
        ];

        // Process meals and save relationships
        foreach ($meals as $meal) {
            $ingredients = $meal['ingredients'];
            unset($meal['ingredients']);

            // ensure the meal is linked to the default user so user_id is set
            $mealModel = $user->meals()->create($meal);

            // Attach ingredients to the meal
            foreach ($ingredients as $ingredientName) {
                $ingredient = Ingredient::where('name', $ingredientName)->first();
                if ($ingredient) {
                    $mealModel->ingredients()->attach($ingredient->id);
                }
            }
        }
    }
}
